(cl:defpackage excavator_msgs-srv
  (:use )
  (:export
   "SETMODE"
   "<SETMODE-REQUEST>"
   "SETMODE-REQUEST"
   "<SETMODE-RESPONSE>"
   "SETMODE-RESPONSE"
   "SPAWNOBSTACLE"
   "<SPAWNOBSTACLE-REQUEST>"
   "SPAWNOBSTACLE-REQUEST"
   "<SPAWNOBSTACLE-RESPONSE>"
   "SPAWNOBSTACLE-RESPONSE"
  ))

