// Generated by gencpp from file excavator_msgs/ObstacleInfo.msg
// DO NOT EDIT!


#ifndef EXCAVATOR_MSGS_MESSAGE_OBSTACLEINFO_H
#define EXCAVATOR_MSGS_MESSAGE_OBSTACLEINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/PoseStamped.h>
#include <geometry_msgs/Vector3.h>

namespace excavator_msgs
{
template <class ContainerAllocator>
struct ObstacleInfo_
{
  typedef ObstacleInfo_<ContainerAllocator> Type;

  ObstacleInfo_()
    : header()
    , obstacle_id()
    , obstacle_type()
    , distance(0.0)
    , relative_velocity(0.0)
    , ttc(0.0)
    , risk_score(0.0)
    , risk_level(0)
    , pose()
    , velocity_vec()  {
    }
  ObstacleInfo_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , obstacle_id(_alloc)
    , obstacle_type(_alloc)
    , distance(0.0)
    , relative_velocity(0.0)
    , ttc(0.0)
    , risk_score(0.0)
    , risk_level(0)
    , pose(_alloc)
    , velocity_vec(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _obstacle_id_type;
  _obstacle_id_type obstacle_id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _obstacle_type_type;
  _obstacle_type_type obstacle_type;

   typedef float _distance_type;
  _distance_type distance;

   typedef float _relative_velocity_type;
  _relative_velocity_type relative_velocity;

   typedef float _ttc_type;
  _ttc_type ttc;

   typedef float _risk_score_type;
  _risk_score_type risk_score;

   typedef uint8_t _risk_level_type;
  _risk_level_type risk_level;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _velocity_vec_type;
  _velocity_vec_type velocity_vec;





  typedef boost::shared_ptr< ::excavator_msgs::ObstacleInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::excavator_msgs::ObstacleInfo_<ContainerAllocator> const> ConstPtr;

}; // struct ObstacleInfo_

typedef ::excavator_msgs::ObstacleInfo_<std::allocator<void> > ObstacleInfo;

typedef boost::shared_ptr< ::excavator_msgs::ObstacleInfo > ObstacleInfoPtr;
typedef boost::shared_ptr< ::excavator_msgs::ObstacleInfo const> ObstacleInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::excavator_msgs::ObstacleInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::excavator_msgs::ObstacleInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::excavator_msgs::ObstacleInfo_<ContainerAllocator1> & lhs, const ::excavator_msgs::ObstacleInfo_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.obstacle_id == rhs.obstacle_id &&
    lhs.obstacle_type == rhs.obstacle_type &&
    lhs.distance == rhs.distance &&
    lhs.relative_velocity == rhs.relative_velocity &&
    lhs.ttc == rhs.ttc &&
    lhs.risk_score == rhs.risk_score &&
    lhs.risk_level == rhs.risk_level &&
    lhs.pose == rhs.pose &&
    lhs.velocity_vec == rhs.velocity_vec;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::excavator_msgs::ObstacleInfo_<ContainerAllocator1> & lhs, const ::excavator_msgs::ObstacleInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace excavator_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::excavator_msgs::ObstacleInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::excavator_msgs::ObstacleInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::excavator_msgs::ObstacleInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::excavator_msgs::ObstacleInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::excavator_msgs::ObstacleInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::excavator_msgs::ObstacleInfo_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::excavator_msgs::ObstacleInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fd4d72f9487b4c603a524a69bbad426f";
  }

  static const char* value(const ::excavator_msgs::ObstacleInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfd4d72f9487b4c60ULL;
  static const uint64_t static_value2 = 0x3a524a69bbad426fULL;
};

template<class ContainerAllocator>
struct DataType< ::excavator_msgs::ObstacleInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "excavator_msgs/ObstacleInfo";
  }

  static const char* value(const ::excavator_msgs::ObstacleInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::excavator_msgs::ObstacleInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"string obstacle_id\n"
"string obstacle_type\n"
"float32 distance\n"
"float32 relative_velocity\n"
"float32 ttc\n"
"float32 risk_score\n"
"uint8 risk_level\n"
"geometry_msgs/PoseStamped pose\n"
"geometry_msgs/Vector3 velocity_vec\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::excavator_msgs::ObstacleInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::excavator_msgs::ObstacleInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.obstacle_id);
      stream.next(m.obstacle_type);
      stream.next(m.distance);
      stream.next(m.relative_velocity);
      stream.next(m.ttc);
      stream.next(m.risk_score);
      stream.next(m.risk_level);
      stream.next(m.pose);
      stream.next(m.velocity_vec);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObstacleInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::excavator_msgs::ObstacleInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::excavator_msgs::ObstacleInfo_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "obstacle_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.obstacle_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "obstacle_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.obstacle_type);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "relative_velocity: ";
    Printer<float>::stream(s, indent + "  ", v.relative_velocity);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ttc: ";
    Printer<float>::stream(s, indent + "  ", v.ttc);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "risk_score: ";
    Printer<float>::stream(s, indent + "  ", v.risk_score);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "risk_level: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.risk_level);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pose: ";
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "velocity_vec: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.velocity_vec);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXCAVATOR_MSGS_MESSAGE_OBSTACLEINFO_H
