// Generated by gencpp from file excavator_msgs/ObstacleArray.msg
// DO NOT EDIT!


#ifndef EXCAVATOR_MSGS_MESSAGE_OBSTACLEARRAY_H
#define EXCAVATOR_MSGS_MESSAGE_OBSTACLEARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <excavator_msgs/ObstacleInfo.h>

namespace excavator_msgs
{
template <class ContainerAllocator>
struct ObstacleArray_
{
  typedef ObstacleArray_<ContainerAllocator> Type;

  ObstacleArray_()
    : header()
    , obstacles()
    , dominant_risk_level(0)  {
    }
  ObstacleArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , obstacles(_alloc)
    , dominant_risk_level(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::excavator_msgs::ObstacleInfo_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::excavator_msgs::ObstacleInfo_<ContainerAllocator> >> _obstacles_type;
  _obstacles_type obstacles;

   typedef uint8_t _dominant_risk_level_type;
  _dominant_risk_level_type dominant_risk_level;





  typedef boost::shared_ptr< ::excavator_msgs::ObstacleArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::excavator_msgs::ObstacleArray_<ContainerAllocator> const> ConstPtr;

}; // struct ObstacleArray_

typedef ::excavator_msgs::ObstacleArray_<std::allocator<void> > ObstacleArray;

typedef boost::shared_ptr< ::excavator_msgs::ObstacleArray > ObstacleArrayPtr;
typedef boost::shared_ptr< ::excavator_msgs::ObstacleArray const> ObstacleArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::excavator_msgs::ObstacleArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::excavator_msgs::ObstacleArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::excavator_msgs::ObstacleArray_<ContainerAllocator1> & lhs, const ::excavator_msgs::ObstacleArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.obstacles == rhs.obstacles &&
    lhs.dominant_risk_level == rhs.dominant_risk_level;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::excavator_msgs::ObstacleArray_<ContainerAllocator1> & lhs, const ::excavator_msgs::ObstacleArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace excavator_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::excavator_msgs::ObstacleArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::excavator_msgs::ObstacleArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::excavator_msgs::ObstacleArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::excavator_msgs::ObstacleArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::excavator_msgs::ObstacleArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::excavator_msgs::ObstacleArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::excavator_msgs::ObstacleArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "47b96ec652e3bd0352f9dd3764857936";
  }

  static const char* value(const ::excavator_msgs::ObstacleArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x47b96ec652e3bd03ULL;
  static const uint64_t static_value2 = 0x52f9dd3764857936ULL;
};

template<class ContainerAllocator>
struct DataType< ::excavator_msgs::ObstacleArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "excavator_msgs/ObstacleArray";
  }

  static const char* value(const ::excavator_msgs::ObstacleArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::excavator_msgs::ObstacleArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"excavator_msgs/ObstacleInfo[] obstacles\n"
"uint8 dominant_risk_level\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: excavator_msgs/ObstacleInfo\n"
"std_msgs/Header header\n"
"string obstacle_id\n"
"string obstacle_type\n"
"float32 distance\n"
"float32 relative_velocity\n"
"float32 ttc\n"
"float32 risk_score\n"
"uint8 risk_level\n"
"geometry_msgs/PoseStamped pose\n"
"geometry_msgs/Vector3 velocity_vec\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::excavator_msgs::ObstacleArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::excavator_msgs::ObstacleArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.obstacles);
      stream.next(m.dominant_risk_level);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObstacleArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::excavator_msgs::ObstacleArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::excavator_msgs::ObstacleArray_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "obstacles: ";
    if (v.obstacles.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.obstacles.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::excavator_msgs::ObstacleInfo_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.obstacles[i]);
    }
    if (v.obstacles.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "dominant_risk_level: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.dominant_risk_level);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXCAVATOR_MSGS_MESSAGE_OBSTACLEARRAY_H
