// Generated by gencpp from file excavator_msgs/RiskState.msg
// DO NOT EDIT!


#ifndef EXCAVATOR_MSGS_MESSAGE_RISKSTATE_H
#define EXCAVATOR_MSGS_MESSAGE_RISKSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace excavator_msgs
{
template <class ContainerAllocator>
struct RiskState_
{
  typedef RiskState_<ContainerAllocator> Type;

  RiskState_()
    : header()
    , current_level(0)
    , min_distance(0.0)
    , min_ttc(0.0)
    , primary_threat_id()  {
    }
  RiskState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , current_level(0)
    , min_distance(0.0)
    , min_ttc(0.0)
    , primary_threat_id(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _current_level_type;
  _current_level_type current_level;

   typedef float _min_distance_type;
  _min_distance_type min_distance;

   typedef float _min_ttc_type;
  _min_ttc_type min_ttc;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _primary_threat_id_type;
  _primary_threat_id_type primary_threat_id;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(LEVEL_LOW)
  #undef LEVEL_LOW
#endif
#if defined(_WIN32) && defined(LEVEL_MEDIUM)
  #undef LEVEL_MEDIUM
#endif
#if defined(_WIN32) && defined(LEVEL_HIGH)
  #undef LEVEL_HIGH
#endif

  enum {
    LEVEL_LOW = 0u,
    LEVEL_MEDIUM = 1u,
    LEVEL_HIGH = 2u,
  };


  typedef boost::shared_ptr< ::excavator_msgs::RiskState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::excavator_msgs::RiskState_<ContainerAllocator> const> ConstPtr;

}; // struct RiskState_

typedef ::excavator_msgs::RiskState_<std::allocator<void> > RiskState;

typedef boost::shared_ptr< ::excavator_msgs::RiskState > RiskStatePtr;
typedef boost::shared_ptr< ::excavator_msgs::RiskState const> RiskStateConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::excavator_msgs::RiskState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::excavator_msgs::RiskState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::excavator_msgs::RiskState_<ContainerAllocator1> & lhs, const ::excavator_msgs::RiskState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.current_level == rhs.current_level &&
    lhs.min_distance == rhs.min_distance &&
    lhs.min_ttc == rhs.min_ttc &&
    lhs.primary_threat_id == rhs.primary_threat_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::excavator_msgs::RiskState_<ContainerAllocator1> & lhs, const ::excavator_msgs::RiskState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace excavator_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::excavator_msgs::RiskState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::excavator_msgs::RiskState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::excavator_msgs::RiskState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::excavator_msgs::RiskState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::excavator_msgs::RiskState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::excavator_msgs::RiskState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::excavator_msgs::RiskState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "56281077a6d41cbba414fc9ed69c92af";
  }

  static const char* value(const ::excavator_msgs::RiskState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x56281077a6d41cbbULL;
  static const uint64_t static_value2 = 0xa414fc9ed69c92afULL;
};

template<class ContainerAllocator>
struct DataType< ::excavator_msgs::RiskState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "excavator_msgs/RiskState";
  }

  static const char* value(const ::excavator_msgs::RiskState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::excavator_msgs::RiskState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"uint8 LEVEL_LOW=0\n"
"uint8 LEVEL_MEDIUM=1\n"
"uint8 LEVEL_HIGH=2\n"
"uint8 current_level\n"
"float32 min_distance\n"
"float32 min_ttc\n"
"string primary_threat_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::excavator_msgs::RiskState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::excavator_msgs::RiskState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.current_level);
      stream.next(m.min_distance);
      stream.next(m.min_ttc);
      stream.next(m.primary_threat_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RiskState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::excavator_msgs::RiskState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::excavator_msgs::RiskState_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "current_level: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.current_level);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "min_distance: ";
    Printer<float>::stream(s, indent + "  ", v.min_distance);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "min_ttc: ";
    Printer<float>::stream(s, indent + "  ", v.min_ttc);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "primary_threat_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.primary_threat_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXCAVATOR_MSGS_MESSAGE_RISKSTATE_H
