// Generated by gencpp from file excavator_msgs/SetMode.msg
// DO NOT EDIT!


#ifndef EXCAVATOR_MSGS_MESSAGE_SETMODE_H
#define EXCAVATOR_MSGS_MESSAGE_SETMODE_H

#include <ros/service_traits.h>


#include <excavator_msgs/SetModeRequest.h>
#include <excavator_msgs/SetModeResponse.h>


namespace excavator_msgs
{

struct SetMode
{

typedef SetModeRequest Request;
typedef SetModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetMode
} // namespace excavator_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::excavator_msgs::SetMode > {
  static const char* value()
  {
    return "1393b8f659688f5f0d86f35948597ef1";
  }

  static const char* value(const ::excavator_msgs::SetMode&) { return value(); }
};

template<>
struct DataType< ::excavator_msgs::SetMode > {
  static const char* value()
  {
    return "excavator_msgs/SetMode";
  }

  static const char* value(const ::excavator_msgs::SetMode&) { return value(); }
};


// service_traits::MD5Sum< ::excavator_msgs::SetModeRequest> should match
// service_traits::MD5Sum< ::excavator_msgs::SetMode >
template<>
struct MD5Sum< ::excavator_msgs::SetModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::excavator_msgs::SetMode >::value();
  }
  static const char* value(const ::excavator_msgs::SetModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::excavator_msgs::SetModeRequest> should match
// service_traits::DataType< ::excavator_msgs::SetMode >
template<>
struct DataType< ::excavator_msgs::SetModeRequest>
{
  static const char* value()
  {
    return DataType< ::excavator_msgs::SetMode >::value();
  }
  static const char* value(const ::excavator_msgs::SetModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::excavator_msgs::SetModeResponse> should match
// service_traits::MD5Sum< ::excavator_msgs::SetMode >
template<>
struct MD5Sum< ::excavator_msgs::SetModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::excavator_msgs::SetMode >::value();
  }
  static const char* value(const ::excavator_msgs::SetModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::excavator_msgs::SetModeResponse> should match
// service_traits::DataType< ::excavator_msgs::SetMode >
template<>
struct DataType< ::excavator_msgs::SetModeResponse>
{
  static const char* value()
  {
    return DataType< ::excavator_msgs::SetMode >::value();
  }
  static const char* value(const ::excavator_msgs::SetModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EXCAVATOR_MSGS_MESSAGE_SETMODE_H
