// Generated by gencpp from file excavator_msgs/SpawnObstacle.msg
// DO NOT EDIT!


#ifndef EXCAVATOR_MSGS_MESSAGE_SPAWNOBSTACLE_H
#define EXCAVATOR_MSGS_MESSAGE_SPAWNOBSTACLE_H

#include <ros/service_traits.h>


#include <excavator_msgs/SpawnObstacleRequest.h>
#include <excavator_msgs/SpawnObstacleResponse.h>


namespace excavator_msgs
{

struct SpawnObstacle
{

typedef SpawnObstacleRequest Request;
typedef SpawnObstacleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SpawnObstacle
} // namespace excavator_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::excavator_msgs::SpawnObstacle > {
  static const char* value()
  {
    return "65854cfe8780150fdff4825667aa09ca";
  }

  static const char* value(const ::excavator_msgs::SpawnObstacle&) { return value(); }
};

template<>
struct DataType< ::excavator_msgs::SpawnObstacle > {
  static const char* value()
  {
    return "excavator_msgs/SpawnObstacle";
  }

  static const char* value(const ::excavator_msgs::SpawnObstacle&) { return value(); }
};


// service_traits::MD5Sum< ::excavator_msgs::SpawnObstacleRequest> should match
// service_traits::MD5Sum< ::excavator_msgs::SpawnObstacle >
template<>
struct MD5Sum< ::excavator_msgs::SpawnObstacleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::excavator_msgs::SpawnObstacle >::value();
  }
  static const char* value(const ::excavator_msgs::SpawnObstacleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::excavator_msgs::SpawnObstacleRequest> should match
// service_traits::DataType< ::excavator_msgs::SpawnObstacle >
template<>
struct DataType< ::excavator_msgs::SpawnObstacleRequest>
{
  static const char* value()
  {
    return DataType< ::excavator_msgs::SpawnObstacle >::value();
  }
  static const char* value(const ::excavator_msgs::SpawnObstacleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::excavator_msgs::SpawnObstacleResponse> should match
// service_traits::MD5Sum< ::excavator_msgs::SpawnObstacle >
template<>
struct MD5Sum< ::excavator_msgs::SpawnObstacleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::excavator_msgs::SpawnObstacle >::value();
  }
  static const char* value(const ::excavator_msgs::SpawnObstacleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::excavator_msgs::SpawnObstacleResponse> should match
// service_traits::DataType< ::excavator_msgs::SpawnObstacle >
template<>
struct DataType< ::excavator_msgs::SpawnObstacleResponse>
{
  static const char* value()
  {
    return DataType< ::excavator_msgs::SpawnObstacle >::value();
  }
  static const char* value(const ::excavator_msgs::SpawnObstacleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EXCAVATOR_MSGS_MESSAGE_SPAWNOBSTACLE_H
