// Generated by gencpp from file excavator_msgs/SpawnObstacleRequest.msg
// DO NOT EDIT!


#ifndef EXCAVATOR_MSGS_MESSAGE_SPAWNOBSTACLEREQUEST_H
#define EXCAVATOR_MSGS_MESSAGE_SPAWNOBSTACLEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace excavator_msgs
{
template <class ContainerAllocator>
struct SpawnObstacleRequest_
{
  typedef SpawnObstacleRequest_<ContainerAllocator> Type;

  SpawnObstacleRequest_()
    : obstacle_type()
    , pose()  {
    }
  SpawnObstacleRequest_(const ContainerAllocator& _alloc)
    : obstacle_type(_alloc)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _obstacle_type_type;
  _obstacle_type_type obstacle_type;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::excavator_msgs::SpawnObstacleRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::excavator_msgs::SpawnObstacleRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SpawnObstacleRequest_

typedef ::excavator_msgs::SpawnObstacleRequest_<std::allocator<void> > SpawnObstacleRequest;

typedef boost::shared_ptr< ::excavator_msgs::SpawnObstacleRequest > SpawnObstacleRequestPtr;
typedef boost::shared_ptr< ::excavator_msgs::SpawnObstacleRequest const> SpawnObstacleRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::excavator_msgs::SpawnObstacleRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::excavator_msgs::SpawnObstacleRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::excavator_msgs::SpawnObstacleRequest_<ContainerAllocator1> & lhs, const ::excavator_msgs::SpawnObstacleRequest_<ContainerAllocator2> & rhs)
{
  return lhs.obstacle_type == rhs.obstacle_type &&
    lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::excavator_msgs::SpawnObstacleRequest_<ContainerAllocator1> & lhs, const ::excavator_msgs::SpawnObstacleRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace excavator_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::excavator_msgs::SpawnObstacleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::excavator_msgs::SpawnObstacleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::excavator_msgs::SpawnObstacleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::excavator_msgs::SpawnObstacleRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::excavator_msgs::SpawnObstacleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::excavator_msgs::SpawnObstacleRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::excavator_msgs::SpawnObstacleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ad2e264059dbd904f871b8c4b9511ddb";
  }

  static const char* value(const ::excavator_msgs::SpawnObstacleRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xad2e264059dbd904ULL;
  static const uint64_t static_value2 = 0xf871b8c4b9511ddbULL;
};

template<class ContainerAllocator>
struct DataType< ::excavator_msgs::SpawnObstacleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "excavator_msgs/SpawnObstacleRequest";
  }

  static const char* value(const ::excavator_msgs::SpawnObstacleRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::excavator_msgs::SpawnObstacleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string obstacle_type\n"
"geometry_msgs/Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::excavator_msgs::SpawnObstacleRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::excavator_msgs::SpawnObstacleRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.obstacle_type);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SpawnObstacleRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::excavator_msgs::SpawnObstacleRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::excavator_msgs::SpawnObstacleRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "obstacle_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.obstacle_type);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pose: ";
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXCAVATOR_MSGS_MESSAGE_SPAWNOBSTACLEREQUEST_H
