// Generated by gencpp from file excavator_msgs/SpawnObstacleResponse.msg
// DO NOT EDIT!


#ifndef EXCAVATOR_MSGS_MESSAGE_SPAWNOBSTACLERESPONSE_H
#define EXCAVATOR_MSGS_MESSAGE_SPAWNOBSTACLERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace excavator_msgs
{
template <class ContainerAllocator>
struct SpawnObstacleResponse_
{
  typedef SpawnObstacleResponse_<ContainerAllocator> Type;

  SpawnObstacleResponse_()
    : success(false)
    , obstacle_id()  {
    }
  SpawnObstacleResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , obstacle_id(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _obstacle_id_type;
  _obstacle_id_type obstacle_id;





  typedef boost::shared_ptr< ::excavator_msgs::SpawnObstacleResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::excavator_msgs::SpawnObstacleResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SpawnObstacleResponse_

typedef ::excavator_msgs::SpawnObstacleResponse_<std::allocator<void> > SpawnObstacleResponse;

typedef boost::shared_ptr< ::excavator_msgs::SpawnObstacleResponse > SpawnObstacleResponsePtr;
typedef boost::shared_ptr< ::excavator_msgs::SpawnObstacleResponse const> SpawnObstacleResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::excavator_msgs::SpawnObstacleResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::excavator_msgs::SpawnObstacleResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::excavator_msgs::SpawnObstacleResponse_<ContainerAllocator1> & lhs, const ::excavator_msgs::SpawnObstacleResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.obstacle_id == rhs.obstacle_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::excavator_msgs::SpawnObstacleResponse_<ContainerAllocator1> & lhs, const ::excavator_msgs::SpawnObstacleResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace excavator_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::excavator_msgs::SpawnObstacleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::excavator_msgs::SpawnObstacleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::excavator_msgs::SpawnObstacleResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::excavator_msgs::SpawnObstacleResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::excavator_msgs::SpawnObstacleResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::excavator_msgs::SpawnObstacleResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::excavator_msgs::SpawnObstacleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e093f2c3f11754f4ca78369b68bac43a";
  }

  static const char* value(const ::excavator_msgs::SpawnObstacleResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe093f2c3f11754f4ULL;
  static const uint64_t static_value2 = 0xca78369b68bac43aULL;
};

template<class ContainerAllocator>
struct DataType< ::excavator_msgs::SpawnObstacleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "excavator_msgs/SpawnObstacleResponse";
  }

  static const char* value(const ::excavator_msgs::SpawnObstacleResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::excavator_msgs::SpawnObstacleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string obstacle_id\n"
"\n"
;
  }

  static const char* value(const ::excavator_msgs::SpawnObstacleResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::excavator_msgs::SpawnObstacleResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.obstacle_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SpawnObstacleResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::excavator_msgs::SpawnObstacleResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::excavator_msgs::SpawnObstacleResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "obstacle_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.obstacle_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXCAVATOR_MSGS_MESSAGE_SPAWNOBSTACLERESPONSE_H
